cflags = -std=c99 -O2 
dflags = -std=c99 -g
includes = -I ../iostring -I ../structures/has
libs = ../../lib -liostring -lHashQ
source = $(wildcard *.c) ../structures/nodos/nodoarbol.c 
output = ../../bin/practica9

build :
	gcc $(cflags) $(source) -o $(output) $(includes) -L $(libs)
	@echo "Compilo Exitosamente!!!"
run :
	$(output).execflags = -std=c99 -O2 
dflags = -std=c99 -g
includes = -I ../iostring -I ../structures/has
libs = ../../lib -liostring -lHashQ
source = $(wildcard *.c) ../structures/nodos/nodoarbol.c 
output = ../../bin/practica9

build :
	gcc $(cflags) $(source) -o $(output) $(includes) -L $(libs)
	@echo "Compilo Exitosamente!!!"
run :
	$(output).exe